version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./artifacts:/app/artifacts
      - ./mlruns:/app/mlruns
      - ./governance:/app/governance
      - ./mlruns:/Users/vizzdd/Documents/FDE/diabetes-readmission/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.13.0
    ports:
      - "5050:5000"
    environment:
      - MLFLOW_ALLOW_FILE_STORE=true
      - MLFLOW_SERVER_DISABLE_SECURITY_MIDDLEWARE=true
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./mlruns:/Users/vizzdd/Documents/FDE/diabetes-readmission/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow/mlruns --default-artifact-root /mlflow/mlruns

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
